<<<<<<< Updated upstream
spring.datasource.url=jdbc:mysql://10.206.63.235:3306/astracine?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=astracine
spring.datasource.password=123456

#Default security
spring.security.user.name=admin
spring.security.user.password=admin

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# File Upload Configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Cloudinary Configuration
cloudinary.cloud-name=diw7pjuhp
cloudinary.api-key=452848438579663
cloudinary.api-secret=MnuzxOne4lZ14-KCeNuj9z1ITgQ
cloudinary.folder=astracine/posters

# Server Configuration
server.port=8080

# Logging
logging.level.org.springframework.web=INFO
logging.level.com.astracine.backend=DEBUG
=======


# 1. Cấu hình kết nối MySQL
# 'astracine' là tên database bạn đã tạo trong câu lệnh SQL trước đó
spring.datasource.url=jdbc:mysql://localhost:3306/astracine?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=1234


# spring.datasource.url=jdbc:mysql://10.206.63.235:3306/astracine?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh
# spring.datasource.username=astracine
# spring.datasource.password=123456

# spring.jpa.show-sql=true

# 2. Cấu hình JPA / Hibernate
# 'update': Tự động cập nhật bảng nếu Entity thay đổi (Rất tiện khi Dev)
# 'validate': Chỉ kiểm tra xem Code và DB có khớp nhau không
spring.jpa.hibernate.ddl-auto=update

# Hiển thị câu lệnh SQL trong Console để dễ debug (Xem nó insert ghế thế nào)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Database Platform
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#Default security
spring.security.user.name=admin
spring.security.user.password=admin
>>>>>>> Stashed changes
